# Generated by Django 5.1.5 on 2025-01-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
